### ISSUE TITLE
IntelliJ IDEA Community Edition 2019.2.3 not working at all

### ISSUE THREAD

**Issue by FaruNL** [xylo/intellij-postfix-templates#147] opened 2019-10-25 02:31 UTC
When I try to use de `ctrl + space` in the editor and try to use the postfix completion; it just doesn't show any suggestion at all. 

**For instance:**
![idea64_oC0cFt1iwW](https://user-images.githubusercontent.com/34426099/67538537-fced7280-f6a4-11e9-94ab-2ab722074717.png)

**Or:**
![idea64_m69XFKS9er](https://user-images.githubusercontent.com/34426099/67538554-0545ad80-f6a5-11e9-8d06-fbb981468a5f.png)

Y tried the postfix completion in PyCharm, but somehow it works there.
I notice something:

**Pycharm with the plugin disabled:**
![pycharm_without_plugin](https://user-images.githubusercontent.com/34426099/67538202-1510c200-f6a4-11e9-8898-c13b81cc12d2.png)

**Pycharm with the plugin enabled:**
![pycharm_with_plugin](https://user-images.githubusercontent.com/34426099/67538218-307bcd00-f6a4-11e9-85f0-504891322f6c.png)

**But in IntelliJ IDEA it just look the same, whether I have the plugin enabled or not:**
![idea_without_plugin](https://user-images.githubusercontent.com/34426099/67538334-7fc1fd80-f6a4-11e9-8d55-9402baeaeb8d.png)

**Comment by xylo** [comment] 2019-10-25 06:09
I'm sorry.  The plugin is still a bit unintuitive.  I guess that the templates files have not been activated in your IDEA.  To activate them go to the plugin settings (File->Settings->Editor->Custom Postfix Templates) and press OK or Apply.  Afterwards the templates should be available.

**Comment by FaruNL** [comment] 2019-10-25 11:39
Hi, thanks for replying, ufortunatly this doesn't work, the "apply" button seems not working even if I uncheck some Java template.
And if I just press the "Ok" button (without changing any conf in the window), it does nothing.

I just remember that when I first installed in IDEA I didn't click on Apply, however I did click it in PyCharm.
In IDEA it seems that there's no way to "reapply" de setting (to activate the templates) once you ignored it.

Still, thanks for the reply, I will try another things to make it work in the mean time.

**Comment by xylo** [comment] 2019-10-25 13:19
Hm, interesting.  Oh, you also have to make sure that the postfix completion is activated in File->Settings->Editor->General->Postfix Completion (in case you deactivated it for your tests).

What happens if you create or change a custom template?  That should also lead to a reload of the templates.
To do so, press shift+alt+P select to create or to open a user template file.  When the template file opened press control+S and close the file again or switch back to the previous editor tab.  Now you should have the example template that can be applied.

**Comment by FaruNL** [comment] 2019-10-25 15:07
Hmm, Maybe it's some messed up setting in my IDEA and not the plugin itself?

I tried the steps you mentioned:
![BQhle3pfqh](https://user-images.githubusercontent.com/34426099/67582183-e0862000-f70e-11e9-8c34-a8634075632e.gif)

Oh by the way, thanks for taking time to reply. 
Your plugin it's awesome nevertheless.

**Comment by peng051410** [comment] 2019-10-28 06:25
@FaruNL reinstall this plugin solve it.

**Comment by xylo** [comment] 2019-10-28 10:07
@FaruNL You did everything correctly. I'm sorry, but I have no ideas anymore.

**Comment by FaruNL** [comment] 2019-10-28 11:51
> gin solve it.

Yeap, I did it several times at this point, but nothing seems to work. Thanks for the try tho

**Comment by tldzyx** [comment] 2019-11-11 02:28
It's also not work in 2019.2.4

**Comment by xylo** [comment] 2019-11-11 12:13
> Intellij IDEA 2019.2.4 with version 2.10.10.192 doesn't work.
> 
> Intellij IDEA 2019.2.2 with version 2.10.7.192 is working.
> 
> Intellij IDEA 2019.2.4 with version 2.10.7.192 is working, too.

Oh, that's interesting.  Thanks a lot for this hint!

**Comment by alain57** [comment] 2019-11-20 17:37
I'm using the latest EAP/beta version of intellij and the plugin seems quite unstable :( 
unfortunatelly I have no logs to provide

I installed the plugin
enabled it and added a customize file for java where I wrote some postfix commands.
and the postfix completion menu of intellij stay like defeaut.. 
But some minutes later (if lucky not always) the postfix completion view contains a lot more entries (as it displays the one from this plugin)

I don't know if there is a delay in the processing that takes a long time or if there is something going wrong

But I see no exception :/ 

I alos noticed that the postfix completion view is not refreshed after you disable some entries on the plugin setting page.


I hope a solution will be found :) as I found this plugin so much more useful than the defaut postfix

**Comment by olivergondza** [comment] 2019-12-17 08:13
I am experiencing this since an update (of IDE, plugin or both, not sure). The intellij completions works, but no completions from the plugin are offered (`.var` vs. `.val` demonstrates that nicely). Updating completions ("Update Now") completes without complaining.

This is what is being logged on IDEA startup (I do not know if it was not there back when things worked):

```
2019-12-17 09:02:31,876 [  11936]   WARN -    org.reflections.Reflections - could not get type for name org.jetbrains.plugins.scala.lang.completion.postfix.templates.ScalaStringBasedPostfixTemplate from any class loader 
org.reflections.ReflectionsException: could not get type for name org.jetbrains.plugins.scala.lang.completion.postfix.templates.ScalaStringBasedPostfixTemplate
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at de.endrullis.idea.postfixtemplates.languages.SupportedLanguages.getLangs(SupportedLanguages.java:25)
	at de.endrullis.idea.postfixtemplates.languages.SupportedLanguages.<clinit>(SupportedLanguages.java:42)
	at de.endrullis.idea.postfixtemplates.utils.CptUpdateUtils$1.run(CptUpdateUtils.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.lang.completion.postfix.templates.ScalaStringBasedPostfixTemplate
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:307)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
	... 22 more
2019-12-17 09:02:31,878 [  11938]   WARN -    org.reflections.Reflections - could not get type for name org.jetbrains.plugins.scala.lang.completion.postfix.templates.ScalaStringBasedPostfixTemplate from any class loader 
org.reflections.ReflectionsException: could not get type for name org.jetbrains.plugins.scala.lang.completion.postfix.templates.ScalaStringBasedPostfixTemplate
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at de.endrullis.idea.postfixtemplates.languages.SupportedLanguages.getLangs(SupportedLanguages.java:25)
	at de.endrullis.idea.postfixtemplates.languages.SupportedLanguages.<clinit>(SupportedLanguages.java:42)
	at de.endrullis.idea.postfixtemplates.utils.CptUpdateUtils$1.run(CptUpdateUtils.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.lang.completion.postfix.templates.ScalaStringBasedPostfixTemplate PluginClassLoader[de.endrullis.idea.postfixtemplates, 2.10.12.193] com.intellij.ide.plugins.cl.PluginClassLoader@bd3d027
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
	... 22 more
```
(Disabling completions for scala lang does not fix that)

Version:
```
IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.102, built on December 2, 2019
Runtime version: 11.0.5+10 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.4.2-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: BashSupport, Docker, FindBugs-IDEA, GenerateSerializationHelpers, Ivy Plugin, Stapler plugin for IntelliJ IDEA, VisualVMLauncher, com.intellij.plugin.adernov.powershell, com.karateca.jstoolbox, de.endrullis.idea.postfixtemplates, org.asciidoctor.intellij.asciidoc, org.dlangplugin, org.jetbrains.plugins.rest
```

Plugin version: `2.10.12.193`

**Comment by xylo** [comment] 2019-12-17 10:14
OK, I installed all plugins you have, deactivated my Scala plugins and tested the CPT plugin, but everything works fine for me.  I'm also using a 64 bit Linux system with Java 11, and the same version of IDEA and the CPT plugin.  The only difference I see is that my IDEA version runs with "OpenJDK 64-Bit Server VM by JetBrains s.r.o".

So my guess is that the org.reflections.Reflections library does not work well with the Oracle JRE 11.  Looks like I have to replace the library again.  I created a new issue for that: #150

**Comment by xylo** [comment] 2019-12-18 18:55
I hope I fixed this issue in 2.10.13.  Can someone test it?

**Comment by olivergondza** [comment] 2019-12-19 10:18
I there something special I need to do to get it updated? Marketplace in IDEA does not recognize anything more recent than 2.10.12.193 from Dec 18 2019. Thanks!

**Comment by xylo** [comment] 2019-12-19 12:18
Dec 18 is the correct one. However, the version should be 2.10.13.193 as on this page: https://plugins.jetbrains.com/plugin/9862-custom-postfix-templates/update/74627

**Comment by olivergondza** [comment] 2019-12-19 13:56
I speculate this can be because my IDEA is older (Build #IC-193.5233.102) than now required (193.5662). Will test once there are packages to upgrade the IDEA.

**Comment by xylo** [comment] 2019-12-20 09:04
You can already upgrade IDEA.  193.5662 is the latest stable IDEA release (2019.3.1).

**Comment by xylo** [comment] 2020-01-14 15:46
I assume this bug is fixed in the latest release. So I close this issue now.

**Comment by thekalinga** [comment] 2020-01-14 17:38
Tried in the following version. The plugin does not work

```
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-171-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 7966M
Cores: 4
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: DBN, Docker, FindBugs-IDEA, Lombook Plugin, com.intellij.bigdecimal-folding, com.vladsch.idea.multimarkdown, de.endrullis.idea.postfixtemplates, in.1ton.idea.spring.assistant.plugin, org.asciidoctor.intellij.asciidoc, org.mapstruct.intellij
```

**Comment by thekalinga** [comment] 2020-01-14 17:43
Even after using latest version of plugin

**Comment by thekalinga** [comment] 2020-01-18 13:14
@xylo Any idea on how to debug and make it work?

**Comment by thekalinga** [comment] 2020-01-18 16:07
BTW, I installed IntelliJ using snap store. Not directly

**Comment by xylo** [comment] 2020-01-19 17:57
Maybe it's related to the Community Edition.  I just installed this edition, installed the plugin and discovered major problems. :( IDEA hangs when I open the first project.

**Comment by xylo** [comment] 2020-01-19 19:10
OK, I can confirm that the template completion does not work with the Community Edition anymore.

**Comment by thekalinga** [comment] 2020-01-29 14:12
@xylo Do you have any plans of fixing this?

Thanks

**Comment by xylo** [comment] 2020-01-30 18:29
@thekalinga Thanks for reminding me again. I'm currently working on it again.

**Comment by xylo** [comment] 2020-01-30 19:00
Fixed in version 2.10.14.193.

**Closed by xylo** 2020-01-30 19:00 UTC

**Comment by thekalinga** [comment] 2020-01-31 10:13
Thanks a lot

**Comment by AndyWing** [comment] 2020-02-26 05:48
I was able to use CPT in version Android Studio 3.5, but after upgrading to Android Studio3.6
It shows nothing when i tap .

And i cannot install the version.  2.10.14.193, it limit the version Build #193.
But, Android Studio 3.6 is based on Build #AI-192.7142.36.36.6200805.

Is there any way I can solve this problem?

Thanks.

Android Studio 3.6
Build #AI-192.7142.36.36.6200805, built on February 12, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

CPT version : 2.10.10.192
